package model;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

public class Counties {
public static final String[] counties  = new String[]{"Andora", 
	"Zjednoczone Emiraty Arabskie", 
	"Afganistan", 
	"Antigua and Barbuda", 
	"Anguilla", 
	"Albania", 
	"Armenia", 
	"Antyle Holenderskie", 
	"Angola", 
	"Antarctica", 
	"Argentyna", 
	"American Samoa", 
	"Austria", 
	"Australia", 
	"Aruba", 
	"?land Islands", 
	"Azerbejd¿an", 
	"Boœnia i Hercegowina", 
	"Barbados", 
	"Bangladesz", 
	"Belgia", 
	"Burkina Faso", 
	"Bu³garia", 
	"Bahrajn", 
	"Burundi", 
	"Benin", 
	"Saint Barthélemy", 
	"Bermudy", 
	"Brunei", 
	"Boliwia", 
	"Bonaire, Sint Eustatius and Saba", 
	"Brazylia", 
	"Bahamy", 
	"Bhutan", 
	"Bouvet Island", 
	"Botswana", 
	"Bia³oruœ", 
	"Belize", 
	"Kanada", 
	"Cocos Islands", 
	"The Democratic Republic Of Congo", 
	"Republika Œrodkowoafrykañska", 
	"Kongo", 
	"Szwajcaria", 
	"Wybrze¿e Koœci S³oniowej", 
	"Cook Islands", 
	"Chile", 
	"Kamerun", 
	"Chiny", 
	"Kolumbia", 
	"Kostaryka", 
	"Kuba", 
	"Republika Zielonego Przyl¹dka", 
	"Curaçao", 
	"Christmas Island", 
	"Cypr", 
	"Republika Czeska", 
	"Niemcy", 
	"D¿ibuti", 
	"Dania", 
	"Dominika", 
	"Republika Dominikany", 
	"Algeria", 
	"Ekwador", 
	"Estonia", 
	"Egipt", 
	"Sahara Zachodnia", 
	"Erytrea", 
	"Hiszpania", 
	"Etiopia", 
	"Finlandia", 
	"Fid¿i", 
	"Falkland Islands", 
	"Mikronezja", 
	"Faroe Islands", 
	"Francja", 
	"Gabon", 
	"Wielka Brytania", 
	"Grenada", 
	"Gruzja", 
	"Gujana Francuska", 
	"Guernsey", 
	"Ghana", 
	"Gibraltar", 
	"Greenland", 
	"Gambia", 
	"Gwinea", 
	"Gwadelupa", 
	"Gwinea Równikowa", 
	"Grecja", 
	"South Georgia And The South Sandwich Islands", 
	"Gwatemala", 
	"Guam", 
	"Gwinea Bissau", 
	"Gujana", 
	"Hong Kong", 
	"Heard Island And McDonald Islands", 
	"Honduras", 
	"Chorwacja", 
	"Haiti", 
	"Wêgry", 
	"Indonezja", 
	"Irlandia", 
	"Izrael", 
	"Isle Of Man", 
	"Indie", 
	"British Indian Ocean Territory", 
	"Irak", 
	"Iran", 
	"Islandia", 
	"W³ochy", 
	"Jersey", 
	"Jamajka", 
	"Jordan", 
	"Japonia", 
	"Kenia", 
	"Kirgistan", 
	"Kambod¿a", 
	"Kiribati", 
	"Komory", 
	"Saint Kitts And Nevis", 
	"Korea Pó³nocna", 
	"Korea Po³udniowa", 
	"Kuwejt", 
	"Cayman Islands", 
	"Kazachstan", 
	"Laos", 
	"Liban", 
	"Saint Lucia", 
	"Liechtenstein", 
	"Sri Lanka", 
	"Liberia", 
	"Lesoto", 
	"Litwa", 
	"Luksemburg", 
	"£otwa", 
	"Libia", 
	"Maroko", 
	"Monako", 
	"Mo³dawia", 
	"Montenegro", 
	"Saint Martin", 
	"Madagaskar", 
	"Marshall Islands", 
	"Macedonia", 
	"Mali", 
	"Myanmar", 
	"Mongolia", 
	"Macao", 
	"Northern Mariana Islands", 
	"Martynika", 
	"Mauretania", 
	"Montserrat", 
	"Malta", 
	"Mauritius", 
	"Maldives", 
	"Malawi", 
	"Meksyk", 
	"Malezja", 
	"Mozambik", 
	"Namibia", 
	"Nowa Kaledonia", 
	"Niger", 
	"Norfolk Island", 
	"Nigeria", 
	"Nikaragua", 
	"Holandia", 
	"Norwegia", 
	"Nepal", 
	"Nauru", 
	"Niue", 
	"Nowa Zelandia", 
	"Oman", 
	"Panama", 
	"Peru", 
	"Polinezja Francuska", 
	"Papua Nowa Gwinea", 
	"Filipiny", 
	"Pakistan", 
	"Polska", 
	"Saint Pierre And Miquelon", 
	"Pitcairn", 
	"Portoryko", 
	"Palestine", 
	"Portugalia", 
	"Palau", 
	"Paragwaj", 
	"Katar", 
	"Reunion", 
	"Rumunia", 
	"Serbia", 
	"Rosja", 
	"Rwanda", 
	"Arabia Saudyjska", 
	"Solomon Islands", 
	"Seszele", 
	"Sudan", 
	"Szwecja", 
	"Singapur", 
	"Saint Helena", 
	"S³owenia", 
	"Svalbard And Jan Mayen", 
	"S³owacja", 
	"Sierra Leone", 
	"San Marino", 
	"Senegal", 
	"Somalia", 
	"Surinam", 
	"Sao Tome And Principe", 
	"Salwador", 
	"Sint Maarten (Dutch part)", 
	"Syria", 
	"Suazi", 
	"Turks And Caicos Islands", 
	"Czad", 
	"Francuskie Terytoria Zamorskie", 
	"Togo", 
	"Tajlandia", 
	"Tad¿ykistan", 
	"Tokelau", 
	"Timor-Leste", 
	"Turkmenistan", 
	"Tunezja", 
	"Tonga", 
	"Turcja", 
	"Trynidad i Tobago", 
	"Tuvalu", 
	"Tajwan", 
	"Tanzania", 
	"Ukraina", 
	"Uganda", 
	"United States Minor Outlying Islands", 
	"Stany Zjednoczone Ameryki", 
	"Urugwaj", 
	"Uzbekistan", 
	"Watykan", 
	"Saint Vincent And The Grenadines", 
	"Wenezuela", 
	"Dziewicze Wyspy Brytyjskie", 
	"Dziewicze Wyspy Stanów Zjednoczonych", 
	"Wietnam", 
	"Vanuatu", 
	"Wallis And Futuna", 
	"Samoa", 
	"Jemen", 
	"Mayotte", 
	"Republika Po³udniowej Afryki", 
	"Zambia", 
	"Zimbabwe", 
};
                
}
